### ISSUE TITLE
Incorrect Brazil geometry?

### ISSUE THREAD

**Issue by gfairchild** [descarteslabs/descarteslabs-python#111]
I'm experiencing an issue where Brazil is not being properly rendered, and I'm not sure if it's something on your end or my end. My code is essentially from your documentation [here](http://descartes-labs-python.readthedocs.io/en/latest/getting_started.html):

```python
from pprint import pprint

import descarteslabs as dl
import matplotlib.pyplot as plt
import shapely.geometry
import cartopy

# Find matches for Brazil
matches = dl.places.find('brazil')
pprint(matches)

# Make it the area of interest
aoi = matches[0]

# Get low res version of this shape
shape = dl.places.shape(aoi['slug'], geom='low')
bbox = shape['bbox']

# Load up the Albers Equal Area projection
central_lat = (bbox[1] + bbox[3]) / 2
central_lon = (bbox[0] + bbox[2]) / 2

lonlat_crs = cartopy.crs.PlateCarree()
albers = cartopy.crs.AlbersEqualArea(central_latitude=central_lat, central_longitude=central_lon)

# Create figure to display the region
fig = plt.figure(figsize=(10,14))
ax = plt.subplot(projection=albers)
shp = shapely.geometry.shape(shape['geometry'])

# When adding a geometry in latlon coordinates, specify the latlon projection
ax.add_geometries([shp], lonlat_crs)

# Set extents in latlon by specifying the projection with `crs`
ax.set_extent((bbox[0], bbox[2], bbox[1], bbox[3]), crs=lonlat_crs)
ax.gridlines(crs=lonlat_crs)
plt.show()
```

Here's the resulting image:

![screen shot 2017-06-14 at 9 52 41 am](https://user-images.githubusercontent.com/2835900/27144695-c14f7d0a-50e7-11e7-8081-a66f992b56c2.png)

If I ask to display China, for example:

```python
matches = dl.places.find('china')
```

It works:

![screen shot 2017-06-14 at 9 53 19 am](https://user-images.githubusercontent.com/2835900/27144713-d19834ae-50e7-11e7-82fe-ab17c4162945.png)

Likewise, Australia also works:

```python
matches = dl.places.find('australia')
```

![screen shot 2017-06-14 at 9 54 06 am](https://user-images.githubusercontent.com/2835900/27144736-daed9fd0-50e7-11e7-9566-0d09c4519244.png)

What's going on here?

**Comment by samskillman** [comment]
Hi @gfairchild, looks like the "low" resolution geom is coming up a bit odd. I've found that if I take your script and either request "medium" or when I add the shapely geometry to the axis to use shp.buffer(0), the issue goes away. We'll work to get this fixed so that's not needed, but for now that should work. cc @aliasmrchips

**Comment by gfairchild** [comment]
Great! Thanks for the quick response. We'll use medium until this gets fixed.

**Comment by aliasmrchips** [comment]
Interestingly, the shape rendered fine with folium. I went ahead and "buffered" the low geometry and verified using the script above.
