### ISSUE TITLE
`dl.metadata.sources()` has some inconsistencies

### ISSUE THREAD

**Issue by gfairchild** [descarteslabs/descarteslabs-python#112]
I'm looking at the available imagery sources:

```python
from pprint import pprint
import itertools

import descarteslabs as dl

sources = dl.metadata.sources()
groups = {}
for group, items in itertools.groupby(sources, key=lambda v: v['const_id']):
    groups[group] = list(items)
pprint(groups)
```

This generates the following sources:

```
{'CDL': [{'const_id': 'CDL', 'sat_id': 'CDL', 'value': 140}],
 'L5': [{'const_id': 'L5', 'sat_id': 'LANDSAT_4', 'value': 119}],
 'L7': [{'const_id': 'L7', 'sat_id': 'LANDSAT_7', 'value': 112}],
 'L8': [{'const_id': 'L8', 'sat_id': 'LANDSAT_8', 'value': 89}],
 'L8SR': [{'const_id': 'L8SR', 'sat_id': 'L8SR', 'value': 142}],
 'NAIP': [{'const_id': 'NAIP', 'sat_id': 'NAIP', 'value': 121}],
 'S1A': [{'const_id': 'S1A', 'sat_id': 'SENTINEL-1A', 'value': 108}],
 'S1B': [{'const_id': 'S1B', 'sat_id': 'SENTINEL-1B', 'value': 107}],
 'S2A': [{'const_id': 'S2A', 'sat_id': 'S2A', 'value': 111}],
 'S3A': [{'const_id': 'S3A', 'sat_id': 'S3A', 'value': 110}],
 'modis09': [{'const_id': 'modis09', 'sat_id': 'Terra', 'value': 3},
             {'const_id': 'modis09', 'sat_id': 'Aqua', 'value': 4}],
 'srtm': [{'const_id': 'srtm', 'sat_id': 'srtm', 'value': 120}]}
```

However, there are some inconsistencies here:

* There's no `L4`, as shown in the documentation [here](http://descartes-labs-python.readthedocs.io/en/latest/getting_started.html#Searching-for-available-imagery). It looks like the sources have been updated since the documentation was written.
* `L5`'s description is `LANDSAT_4`. Is this a typo?
* What exactly is `L8SR`, and what makes it different from `L8`?
* What is `srtm`?

I guess the broader issue is that `dl.metadata.sources()` doesn't adequately describe each source, and there's no source-specific documentation on http://descartes-labs-python.readthedocs.io/en/latest/ either. I might propose a few things:

* Add another field, perhaps `description`, that includes a human-readable description of the source. This doesn't need to be super extensive, but 1 or 2 sentences would go a long way.
* You could provide URL fields that link to websites with more information about the source. `url_wikipedia`, for example, could provide a link to the Wikipedia article that describes the data source (e.g., https://en.wikipedia.org/wiki/Landsat_8). `url_official` might link to the *official* website of the source (e.g., https://landsat.usgs.gov/landsat-8).
* Add a section on http://descartes-labs-python.readthedocs.io/en/latest/ that describes each data source you guys offer. Each data source could have a description of available bands, spatial resolution, temporal resolution, years in operation, limitations, example use cases, etc.

**Comment by justinwp** [comment]
Closing this as much of this is now documented at [https://catalog.descarteslabs.com](https://catalog.descarteslabs.com).
