### ISSUE TITLE
Fix Tests for No Results

### ISSUE THREAD

**Issue by justinwp** [descarteslabs/descarteslabs-python#15]
Some tests will fail because the test account does not have access to images.

**Comment by justinwp** [comment]
should be partially addressed by #30 for unauthorized requests

**Comment by justinwp** [comment]
Going to leave this open until we can remove: https://github.com/descarteslabs/descarteslabs-python/blob/master/descarteslabs/tests/test_metadata.py#L36

**Comment by aliasmrchips** [comment]
I think we can remove this test for now. Search by sat_id is currently unavailable in the metadata api

**Comment by aliasmrchips** [comment]
The shape test is supported (although the result will be empty for `public`)
https://github.com/descarteslabs/descarteslabs-python/blob/master/descarteslabs/tests/test_metadata.py#L50

**Comment by justinwp** [comment]
see #43

**Comment by justinwp** [comment]
closed by #62
