### ISSUE TITLE
Issue running sample code for new installs of Shapely and Cartopy

### ISSUE THREAD

**Issue by cj2001** [descarteslabs/descarteslabs-python#173]
There is an incompatibility issue between Shapely and Cartopy that has been documented in [Cartopy Issue #805](https://github.com/SciTools/cartopy/issues/805).  Unless you are really lucky to have installed the exact right version of GEOS, cartopy will say `Assertion failed: (0 != cs), function GEOSCoordSeq_getSize_r, file geos_ts_c.cpp, line 3612.` 

Also, if you follow one of the suggestions of 

`pip install shapely cartopy --no-binary shapely --no-binary cartopy` 

(as described in [#783](https://github.com/SciTools/cartopy/issues/738) you will get a segmentation fault.

In order to run the demo code, can you suggest any alternatives to cartopy?

**Comment by bioinfonm** [comment]
I can confirm this error using anaconda 4.4.2 on OS X 10.11.6 with XCode installed. I solved the error by removing both shapely and cartopy. 

Depending on your install you may need to do the following:
```
conda remove shapely
conda remove cartopy
```
or 
```
pip uninstall cartopy
pip uninstall shapely
```

This is followed by 
`pip install shapely cartopy --no-binary shapely --no-binary cartopy`

If you use shapely or cartopy installed from conda you will end up with the same error and have to start over again. 

This is confirmed to work on OS X, Linux Mint, and Windows https://github.com/SciTools/cartopy/issues/738

**Comment by justinwp** [comment]
We have reworked our demos and documentation at https://docs.descarteslabs.com to avoid the use of cartopy. Thanks for reporting.
