### ISSUE TITLE
Product descriptions should be more informative

### ISSUE THREAD

**Issue by cmertes** [descarteslabs/descarteslabs-python#175]
Product descriptions currently do not effectively clarify the differences between products from the same sensor/constellation. IMO these should contain less (or no) historical/background information on the satellites, and instead focus on clarifying the differences in the data product. I would propose the descriptions include:

- Name (and/or link) to analogous data product from image provider, if applicable
e.g. MOD09Q1, Landsat Collection 1 Tier 1, Landsat Precollection L1T 

- Description of data product 
e.g. Landsat precollection L1T scenes are radiometrically calibrated and orthorectified using ground control points and digital elevation model (DEM) data to correct for relief displacement. 
Source: https://landsat.usgs.gov/how-do-i-determine-processing-level-landsat-scene-i-have-downloaded

- High level description of additional data processing by DL
e.g. pansharpening, scaling, etc.

This information is much more relevant to the user and more difficult to discover than what we're currently offering in the description. Happy to help with this.

**Comment by hrfuller** [comment]
Please feel free to submit a PR here! https://github.com/descarteslabs/product-descriptions
