### ISSUE TITLE
Brazil shape is not valid

### ISSUE THREAD

**Issue by karalimck** [descarteslabs/descarteslabs-python#178]
The Brazil shape from `dl.places.shape` is not a valid shapely shape, which causes problems for any shapely-based analyses.

The problem can be reproduced via:

```
import descarteslabs as dl
import shapely
# get Brazil shape
aoi_BR = dl.places.shape('south-america_brazil', geom = 'low')
# convert to shapely
polygon = shapely.geometry.shape(aoi_BR['geometry'])
# see if it's valid
print polygon.is_valid
```
which outputs:
```
Too few points in geometry component at or near point -41.293430000000001 -2.9687749999999999
False
```

The identified point is in a relatively complex river delta system:
<img src="https://user-images.githubusercontent.com/31671893/30757625-968cf40a-9f8c-11e7-9e52-a27b7dd980e1.png" width="300">

The solution of `polygon.buffer(0)` does not solve the problem.

**Comment by aliasmrchips** [comment]
Do you get the same result with `geom='medium'` or `geom='high'`?

**Comment by karalimck** [comment]
Yes, the polygon is not valid for `geom='medium'`and `geom='high'`.
