### ISSUE TITLE
dl.places.find('some-city') returns [] on most of foreign countries

### ISSUE THREAD

**Issue by kenseii** [descarteslabs/descarteslabs-python#211]
The method returns an empty list on most of foreign countries and cities.
>>> dl.places.find('japan')
[{u'name': u'Japan', u'id': 85632429, u'placetype': u'country', u'bbox': [122.934586, 20.422916, 153.987061, 45.522888], u'path': u'continent:asia_country:japan', u'slug': u'asia_japan'}]
>>> dl.places.find('tokyo')
[]
>>> dl.places.find('Tokyo')
[]

Is the beta only working on american cities only or globally?

**Comment by rmsare** [comment]
I've come up against this problem, too, for smaller American cities and towns. Maybe the `locality` placetype is incomplete for now?

For example, San Francisco, CA is an available locality.
```
>>> dl.places.find('san-francisco')
[{u'bbox': [-123.173825, 37.63983, -122.28178, 37.929824],
  u'id': 85922583,
  u'name': u'San Francisco',
  u'path': u'locality:san-francisco',
  u'placetype': u'locality',
  u'slug': u'san-francisco'}]
```
But BIshop, CA isn't. Inyo County, the county Bishop is located in, is a valid place with placetype `county`.
```
>>> dl.places.find('bishop')
[]
>>> dl.places.find('united-states_california_inyo')
[{u'bbox': [-118.790031, 35.786812, -115.648357, 37.464929],
  u'id': 102087577,
  u'name': u'Inyo',
  u'path': u'continent:north-america_country:united-states_region:california_district:sierra-mountains_county:inyo',
  u'placetype': u'county',
  u'slug': u'north-america_united-states_california_sierra-mountains_inyo'}]
>>> dl.places.find('united-states_california_inyo_bishop')
[]
```

Python 2.7.6 with DL client 0.7.0

**Comment by kenseii** [comment]
Is there any other method working like find but maybe more accurate in the library?

**Comment by rmsare** [comment]
Yeah, this looks like a limitation of how `find` handles query strings. 

You're right, there is a workaround. I can find Tokyo (and any other locality) using the `prefix` method of a `Places` object.

```
>>> res = dl.Places().prefix('asia_japan_tokyo', placetype='locality')
>>> res['features'][-1]
{u'bbox' : [ ... ],
 u'geometry' : {...,
 u'type' : u'MultiPolygon'},
u'id' : 102031307,
u'properties' : {u'name' : u'Tokyo', 
...
u'type' : u'Feature'}
```

**Comment by stephaniegott** [comment]
While Places is still available for use in the `descarteslabs` client, it is no longer under active development.
