### ISSUE TITLE
Time format change for 'acquired' field

### ISSUE THREAD

**Issue by HamedAlemo** [descarteslabs/descarteslabs-python#225]
I frequently use the `acquired` field from the `properties` of each scene, but recently noticed that the format that `acquired` is reported has changed. 

For example, in `sentinel-1:GRD` product I have both of the following time formats in the same search result:

`2018-07-23T16:56:48.840811Z`

and 

`2018-08-04T16:56:49.442103+00:00`.

This makes it really hard to work with the time stamp field. It would be great to make them consistent. 

This is part of my code that extracts time:

```
scenes = dl.metadata.search(
                               products = ["sentinel-1:GRD"],
                               start_datetime = start_datetime,
                               end_datetime = end_datetime,
                               geom = json.dumps(tile['geometry'])
                               ) 
for scene in scenes['features']:
    print(scene.properties['acquired'])
```

Sample output:
```
2018-06-05T16:56:45.658432Z
2018-06-17T16:56:46.558685Z
2018-06-29T16:56:47.221125Z
2018-07-11T16:56:47.781165Z
2018-07-23T16:56:48.840811Z
2018-08-04T16:56:49.442103+00:00
2018-08-16T16:56:50.096621+00:00
2018-08-28T16:56:50.626418+00:00
```

**Comment by nikhaldi** [comment]
Thanks for reporting. Timestamp formats will be unified in an upcoming change to the platform.

If you need further assistance with your code feel free to contact support: https://docs.descarteslabs.com/support.html
