### ISSUE TITLE
Upload image or ndarray to someone else's product.

### ISSUE THREAD

**Issue by cpadavis** [descarteslabs/descarteslabs-python#226]
## Feature

I would like to be able to upload to someone else's product using `catalog.upload_image()` or `catalog.upload_ndarray()`. Right now both use `_do_upload`, which makes a call to `namespace_product()`, which will check if *your* namespace is in the product id and will add it if not. But if you want to upload to someone else's namespace it will prepend your namespace, even if you specified theirs in the product_id.

## Priority

Low to moderate.

**Comment by justinwp** [comment]
I believe this has been resolved.
