### ISSUE TITLE
SceneCollection of 0 scenes

### ISSUE THREAD

**Issue by mosegui** [descarteslabs/descarteslabs-python#228]
I am always getting collections of 0 scenes regardless of looking for scenes or metadata. I pass a geojson object as AOI.

I did the authentification and seemed to work correctly.

Sorry for not being more specific, but just any search will return 0 scenes, without any special error or exception.

Does anyone know this problem?

Thanks in advance

**Comment by joaootavio007** [comment]
i was with same problem...


Hi João,

We regret to inform you that your free Descartes Labs platform trial expired.

To ensure continued access please inquire with our sales team about paid tier options. Monthly subscriptions start at $5000/month, discounted 6 month extended trial packages available at $1500/month for qualifying early-stage startups with access to additional datasets and scalable cloud compute APIs.

If you're in Academia or working for a non-profit you can apply for academic tier access at https://www.descarteslabs.com/application.html which is offered at no charge.

Cheers,

send them an email and find out if it's the same problem

**Comment by BBeran** [comment]
@mosegui , our records indicate you signed up at April 25th 2019, 3:12:03 PM and received an automated e-mail that starts with:

### Thank you for creating an account with Descartes Labs

**Before you proceed further,**
If you're not an existing Descartes Labs customer, please contact our [sales team](mailto:sales@descarteslabs.com) or file an academic project proposal [here](https://www.descarteslabs.com/application.html).

Could it have ended in your Spam e-mail folder by any chance?

**Comment by mosegui** [comment]
Cannot find such email anywhere :/. The only correspondence I have with Descartes is the emails I exchanged with you guys due to this issue :(

**Comment by pythlang** [comment]
I have also been experiencing this and have reached out to your team via the several email addresses listed on your company page without a single response. 

Highly disappointing.
