### ISSUE TITLE
setting `colormap_name` on new GenericBand raises BadRequestError

### ISSUE THREAD

**Issue by grahamjeffries** [descarteslabs/descarteslabs-python#229]
## Expected Behavior
According to the [docs](https://docs.descarteslabs.com/descarteslabs/catalog/docs/band.html?highlight=colormap_name#descarteslabs.catalog.GenericBand.colormap_name) a band defined with the `GenericBand` class should accept an attribute `colormap_name`.

## Actual Behavior
Setting the attribute `colormap_name` raises:
```
BadRequestError: {"errors": [{"detail": "colormap_name is not a valid attribute for bands with type other", "source": {"pointer": "/data/attributes/colormap_name"}, "status": "422", "title": "Validation error"}], "jsonapi": {"version": "1.0"}}
```

## Steps to Reproduce

  1. Create a new product
  2. Define a new band with `colormap_name`

```
import from descarteslabs.catalog import GenericBand, DataType, Resolution, ResolutionUnit

band = GenericBand(name='band_name' product_id=<product_id>)
band.data_type = DataType.INT16
band.data_range = (0, 100)
band.display_range = (0, 100)
band.resolution = Resolution(unit=ResolutionUnit.METERS, value=10)
band.band_index = 0
band.color = "Palette"
band.colormap_name = "viridis"
```

## Workarounds
Setting colormap_name manually in the Catalog GUI works.

## Environment
python 3.6.7
descarteslabs 0.26.0

## Severity
minor

**Comment by nikhaldi** [comment]
Thanks for the report. I can confirm that this is a real bug, we'll get it fixed.

**Comment by nikhaldi** [comment]
This is now fixed. Purely a server-side problem, so no update of the client is required.
