### ISSUE TITLE
There is no source distribution on PyPI

### ISSUE THREAD

**Issue by ocefpaf** [descarteslabs/descarteslabs-python#231]
Not everybody install the wheel. Some Linux distros and downstream packagers need the source distribution. It would be nice to have that published at PyPI together with the wheel.

**Comment by ocefpaf** [comment]
Any reasons why this project no longer uploads source distribution?

**Comment by sdelany2** [comment]
> Any reasons why this project no longer uploads source distribution?

We have a source distribution for our [most recent client release](https://github.com/descarteslabs/descarteslabs-python/releases/tag/v1.2.0) on [PyPI](https://pypi.org/project/descarteslabs/).

**Comment by ocefpaf** [comment]
Thanks. I missed that one yesterday.
