### ISSUE TITLE
Raster example fails

### ISSUE THREAD

**Issue by Aycrazy** [descarteslabs/descarteslabs-python#232]
## Expected Behavior
That it works

## Actual Behavior
BadRequestError: {"message":"Input not found for ids: landsat:LC08:PRE:TOAR:meta_LC80330342017072_v1","status_code":400}

## Steps to Reproduce

  1. Get credentials
  2.Set them
  3.Run the example, and watch it fail

**Comment by stephaniegott** [comment]
Closing, feel free to reopen with any additional information.
