### ISSUE TITLE
Why are DeprecationWarnings set to always?

### ISSUE THREAD

**Issue by carderne** [descarteslabs/descarteslabs-python#235]
## Issue
The following three files (all run when you `import descarteslabs as dl`) enable all `DeprecationWarnings`.

https://github.com/descarteslabs/descarteslabs-python/blob/95b287e63d89ee17f866629f1dc0c91f04f213d3/descarteslabs/__init__.py#L58 

https://github.com/descarteslabs/descarteslabs-python/blob/b10305829f1b75587357e6ef71e3463c13ca7718/descarteslabs/client/services/storage/storage.py#L45

https://github.com/descarteslabs/descarteslabs-python/blob/b10305829f1b75587357e6ef71e3463c13ca7718/descarteslabs/client/services/metadata/metadata.py#L60

## Result
This can be seriously annoying, especially in an IPython/Jupyter environment where it's close to impossible to suppress them.
![image](https://user-images.githubusercontent.com/19817302/90119542-3a60e080-dd49-11ea-81db-0015c7b56400.png)

**Comment by carderne** [comment]
Fix:

https://github.com/carderne/descarteslabs-python/commit/40dbbc3a350deedbca3c2872425811b4e2a86c83

**Comment by aliasmrchips** [comment]
In the meantime, you can suppress warnings in your notebooks using 
```
import logging; logging.getLogger().setLevel(logging.INFO); logging.captureWarnings(True)
```

**Comment by gjoseph92** [comment]
Hey @carderne thanks again for reporting. We switched to `FutureWarning`s in c6cf724465faf97841dd60347523b3ee6acae66e, so in version [1.4.1](https://github.com/descarteslabs/descarteslabs-python/releases/tag/v1.4.1) you shouldn't see these warnings anymore after importing `descarteslabs`.
