### ISSUE TITLE
module 'descarteslabs.workflows' has no attribute 'retrieve'

### ISSUE THREAD

**Issue by jens2121** [descarteslabs/descarteslabs-python#239]
## Expected Behavior
Documentation says we need to use 'retrieve' method to retrieve a published workflow.

## Actual Behavior
Retrieve is not a useable attribute with workflows.

`workflow = wf.retrieve(workflow_id)`

It seems 'use' is callable from the workflow, but when use is used, then this also requires further parameters like 'version'

`use() missing 1 required positional argument: 'version'`

**Comment by stephaniegott** [comment]
`wf.retrieve` was removed in version `1.4.0` in favor of `wf.use` as part of large updates to the `Workflow` sharing functionality (see the [changelog](https://github.com/descarteslabs/descarteslabs-python#workflows---changed)). You can find docs for `wf.use` [here](https://docs.descarteslabs.com/descarteslabs/workflows/docs/execution.html#descarteslabs.workflows.models.use).
