### ISSUE TITLE
What is prupose the WorkflowsLayer class of the DLab-python rewrite TileLayer class ?

### ISSUE THREAD

**Issue by funny000** [descarteslabs/descarteslabs-python#243]
## Expected Behavior
When i learning the DLab-python, use it to show image, and have a qusetion, 
rewrite TileLayer of ipyleaflet whether is to load tile data of from DLab-python backend sever?

## Steps to Reproduce

  1.
  2.
  3.

**Comment by jaytcarlson** [comment]
Hi @funny000, and thanks for reaching out. You are correct, the WorkflowsLayer class exists to support visualizations from the Descartes Labs Workflows API, which you can read about here: https://docs.descarteslabs.com/guides/workflows.html

Data cannot be retrieved from the Descartes Labs Platform until you are granted access. If you would like to request access to the Platform, please use this Contact Us form: https://www.descarteslabs.com/company/contact-us/
