### ISSUE TITLE
Update PYPI

### ISSUE THREAD

**Issue by justinwp** [descarteslabs/descarteslabs-python#36]

**Comment by justinwp** [comment]
>Could not find a version that satisfies the requirement descarteslabs (from -r requirements.txt (line 2)) (from versions: ) No matching distribution found for descarteslabs (from -r requirements.txt (line 2))

**Comment by justinwp** [comment]
Docs still need to be updated.

**Comment by samskillman** [comment]
#39 Fixes this issue.  FWIW, I am now using twine to upload. Do you think we should add a note of how to pip install from the latest `master` on github to the documentation?
