### ISSUE TITLE
Retries Obscure Errors

### ISSUE THREAD

**Issue by justinwp** [descarteslabs/descarteslabs-python#37]
A metadata.search() tried for over a minute to tell me it was a bunch of 500s.

```requests.exceptions.RetryError: HTTPSConnectionPool(host='platform-services.descarteslabs.com', port=443): Max retries exceeded with url: /runcible/search (Caused by ResponseError('too many 500 error responses',))```

- Turn off retry on 500?
- Fix server to return what probably should be a 400?

**Comment by samskillman** [comment]
I think we want to keep retry on 500, so having the metadata service return a 400 would be my preference. @aliasmrchips ?
