### ISSUE TITLE
Python 3 error when running login for the first time: NameError: name 'raw_input' is not defined

### ISSUE THREAD

**Issue by gfairchild** [descarteslabs/descarteslabs-python#64]
I'm attempting to run `descarteslabs login` for the first time, and I'm getting the following error:

```
> descarteslabs login
Follow this link to login https://iam.descarteslabs.com/auth/login?refresh_token=true&destination=/auth/refresh_token
Traceback (most recent call last):
  File "[path]/env/bin/descarteslabs", line 42, in <module>
    s = raw_input('...then come back here and paste the generated token: ')
NameError: name 'raw_input' is not defined
```

Looking at https://github.com/descarteslabs/descarteslabs-python/blob/master/descarteslabs/scripts/descarteslabs#L46, this is because you guys are using `raw_input`, which was [renamed in Python 3 to `input`](https://docs.python.org/3/whatsnew/3.0.html#builtins). I'm using Python 3.6, so that explains the error.

**Comment by samskillman** [comment]
Thanks @gfairchild, updating to `master` should now fix the issue.
