### ISSUE TITLE
raster_handler Breaks Compatibility with Python 3

### ISSUE THREAD

**Issue by rarredon** [descarteslabs/descarteslabs-python#91]
Hi guys,

I was recently contacted by Descartes Labs recruiter, Mike Jacobs, for an opening as Python Developer. While doing some research on your company, I somehow stumbled upon this repository. So naturally, I started playing around with your code (hope you don't mind). In the process I found some minor bugs in the file ./descarteslabs/scripts/parser/raster.py that break compatibility with Python 3.

First, on line 50,

```python
for filename, data in response['files'].iteritems():
```

is an issue because Python 3 no longer supports the 'iteritems' method for dictionaries; this method has actually replaced the 'items' method. So I propose replacing 'iteritems' with 'items', as this will run in Python 2 and Python 3 with only slightly different side effects. Otherwise, you can test for Python 3  using `if sys.version_info > (3, 0)` and then call the appropriate method.

Also, lines 51-52 break Python 3 compatibility. The code

```python
    with open(filename, "w") as f:
        f.write(data)
```

raises an error because the variable 'data' is a bytes object (read from a binary file) and `f.write(data)` attempts to write the bytes object to a file which was _not_ opened in binary mode. In Python 2 this wasn't a problem on Unix machines because Unix treats text and binary files the same. However, Python 3 aims to be more platform-independent and requires you to open a file in binary mode if writing bytes objects to the file (see https://docs.python.org/3.6/library/functions.html#open). So my proposal is simply replacing the mode "w" with "wb". 

Anyways, I hope you find this helpful and not too intrusive or annoying :grimacing:. I'm happy to lend a hand and submit a pull request, if you'd like. Let me know if there's anything else I can help with!

Best regards,
Ryan Arredondo

**Comment by samskillman** [comment]
Thanks for the bug report @rarredon . I have a PR open to fix this issue. I decided to use six.iteritems for now, but both of your fixes would have been good too.
